// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzzcomztkiocgjctqgqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6emNvbXp0a2lvY2dqY3RxZ3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTYyODYsImV4cCI6MjA1NTYzMjI4Nn0.Isi7T3bE8xJJFjY2mjXc9BNyhgICfkZaZcLfPPEqv_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);